import './globals.css'
import { Sora } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';

const inter = Sora({ subsets: ['latin'] })

export const metadata = {
  title: 'Next js Task',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
       <Analytics />
      </body>
    </html>
  )
}
